### ISSUE TITLE
Does iOS support only one DoH config?

### ISSUE THREAD

**Issue by derekwei** [paulmillr/encrypted-dns#29]
iOS 14.3 on iPhone 8
When I installed a new DoH config the existed one disappeared. I want to know whether the system support only ONE DoH setting? Thank you.

**Comment by paulmillr** [comment]
yes

**Comment by Tugzrida** [comment]
I was just having a look at this, and it does support multiple at a time. The issue is just with the profile.

The catch is that both the PayloadUUID and PayloadIdentifier at the end of the profile must be unique. It looks like you've got the UUID unique already, but they all have the same identifier of `com.paulmillr.apple-dns`.

If you want I can open a PR making them unique :)

**Comment by paulmillr** [comment]
I don't understand. How is that supposed to work, when you have two servers specified?

**Comment by paulmillr** [comment]
Did you actually test this e.g. did you monitor the traffic? Or you only saw that iOS can contain two profiles at the same time

**Comment by Tugzrida** [comment]
No perhaps I phrased it poorly. At the moment, if you try to install more than one of your profiles, it will remove any other one as they all have the same identifier.

If you change them to have unique identifiers, then you can install multiple profiles at once and change between the DNS server as you wish under the iOS "VPN & Network" settings.

It doesn't use two at once, just lists multiple ones for you to choose from.

**Comment by paulmillr** [comment]
Yeah, that's a feature. If I install Google DNS, I don't want Cloudflare anymore. The "profile selection" you're talking about can simply be emulated by visiting the GitHub page and clicking on a corresponding profile.

**Comment by Tugzrida** [comment]
Well you could use that to change providers, but that requires opening the repo every time.]

Having multiple ready to go and just switching in the iOS settings is way more convenient:

![IMG_49D5A9AAFEFF-1](https://user-images.githubusercontent.com/11975357/111988700-eb8fea80-8b64-11eb-91ec-d8ce0bc33d2d.jpeg)

If you want, then you can pull [my fork](https://github.com/Tugzrida/encrypted-dns) which has unique identifiers now. Otherwise, I'll just leave it there for anyone else interested.

**Comment by paulmillr** [comment]
Thanks Cameron!
